(cl:defpackage scheduler-msg
  (:use )
  (:export
   "<SCHEDULERACTIONGOAL>"
   "SCHEDULERACTIONGOAL"
   "<SCHEDULERACTION>"
   "SCHEDULERACTION"
   "<SCHEDULERACTIONFEEDBACK>"
   "SCHEDULERACTIONFEEDBACK"
   "<SCHEDULERACTIONRESULT>"
   "SCHEDULERACTIONRESULT"
   "<SCHEDULERRESULT>"
   "SCHEDULERRESULT"
   "<SCHEDULERGOAL>"
   "SCHEDULERGOAL"
   "<SCHEDULERFEEDBACK>"
   "SCHEDULERFEEDBACK"
  ))

