; Auto-generated. Do not edit!


(cl:in-package scheduler-msg)


;//! \htmlinclude SchedulerFeedback.msg.html

(cl:defclass <SchedulerFeedback> (roslisp-msg-protocol:ros-message)
  ((value
    :reader value
    :initarg :value
    :type cl:integer
    :initform 0))
)

(cl:defclass SchedulerFeedback (<SchedulerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SchedulerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SchedulerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name scheduler-msg:<SchedulerFeedback> is deprecated: use scheduler-msg:SchedulerFeedback instead.")))

(cl:ensure-generic-function 'value-val :lambda-list '(m))
(cl:defmethod value-val ((m <SchedulerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader scheduler-msg:value-val is deprecated.  Use scheduler-msg:value instead.")
  (value m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SchedulerFeedback>) ostream)
  "Serializes a message object of type '<SchedulerFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'value)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SchedulerFeedback>) istream)
  "Deserializes a message object of type '<SchedulerFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'value) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SchedulerFeedback>)))
  "Returns string type for a message object of type '<SchedulerFeedback>"
  "scheduler/SchedulerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SchedulerFeedback)))
  "Returns string type for a message object of type 'SchedulerFeedback"
  "scheduler/SchedulerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SchedulerFeedback>)))
  "Returns md5sum for a message object of type '<SchedulerFeedback>"
  "b3087778e93fcd34cc8d65bc54e850d1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SchedulerFeedback)))
  "Returns md5sum for a message object of type 'SchedulerFeedback"
  "b3087778e93fcd34cc8d65bc54e850d1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SchedulerFeedback>)))
  "Returns full string definition for message of type '<SchedulerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SchedulerFeedback)))
  "Returns full string definition for message of type 'SchedulerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SchedulerFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SchedulerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SchedulerFeedback
    (cl:cons ':value (value msg))
))
