/* Auto-generated by genmsg_cpp for file /home/robot/ros/elektron_ballcollector/scheduler/msg/SchedulerResult.msg */
#ifndef SCHEDULER_MESSAGE_SCHEDULERRESULT_H
#define SCHEDULER_MESSAGE_SCHEDULERRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace scheduler
{
template <class ContainerAllocator>
struct SchedulerResult_ {
  typedef SchedulerResult_<ContainerAllocator> Type;

  SchedulerResult_()
  : value(0)
  {
  }

  SchedulerResult_(const ContainerAllocator& _alloc)
  : value(0)
  {
  }

  typedef int32_t _value_type;
  int32_t value;


  typedef boost::shared_ptr< ::scheduler::SchedulerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scheduler::SchedulerResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SchedulerResult
typedef  ::scheduler::SchedulerResult_<std::allocator<void> > SchedulerResult;

typedef boost::shared_ptr< ::scheduler::SchedulerResult> SchedulerResultPtr;
typedef boost::shared_ptr< ::scheduler::SchedulerResult const> SchedulerResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::scheduler::SchedulerResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::scheduler::SchedulerResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace scheduler

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::scheduler::SchedulerResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::scheduler::SchedulerResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::scheduler::SchedulerResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b3087778e93fcd34cc8d65bc54e850d1";
  }

  static const char* value(const  ::scheduler::SchedulerResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb3087778e93fcd34ULL;
  static const uint64_t static_value2 = 0xcc8d65bc54e850d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::scheduler::SchedulerResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "scheduler/SchedulerResult";
  }

  static const char* value(const  ::scheduler::SchedulerResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::scheduler::SchedulerResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 value\n\
\n\
";
  }

  static const char* value(const  ::scheduler::SchedulerResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::scheduler::SchedulerResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::scheduler::SchedulerResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SchedulerResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scheduler::SchedulerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::scheduler::SchedulerResult_<ContainerAllocator> & v) 
  {
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SCHEDULER_MESSAGE_SCHEDULERRESULT_H

